language: python

cache: pip

dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

before_install:
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools
  - python -m pip install --upgrade pytest
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.5" ]; then python -m pip install mypy; fi

install:
  - python -m pip install -e .

script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.5" ]; then mypy src/icegrams/__init__.py; fi
  - python -m pytest

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
